import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header>
          <h1 style={{ textAlign: 'center', fontSize: 50 }}>Our App</h1>
          <hr />
          <nav>
            <ul>
              <li>
                <Link href={{ pathname: '/' }}>Home</Link>
              </li>
              <li>
                <Link href={{ pathname: '/about' }}>About</Link>
              </li>
              <li>
                <Link href={{ pathname: '/contact' }}>Contact</Link>
              </li>
            </ul>
          </nav>
          <hr />
        </header>
        {children}
        <footer>
          <p style={{ textAlign: 'center', fontSize: 20 }} >The Footer goes here</p>
        </footer>
      </body>
    </html>
  );
}
