import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavigationBar from "@/app/components/NavBar";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <header>
                    <h1 style={{ textAlign: 'center', fontSize: 50 }}>Our App</h1>
                    <hr />
                    <NavigationBar />
                    <hr />
                </header>
                {children}
                <footer>
                    <p style={{ textAlign: 'center', fontSize: 20 }} >The Footer goes here</p>
                </footer>
            </body>
        </html>
    );
}
